language: python

dist: bionic

sudo: required

services:
  - docker

before_install:
  - docker pull asciidoctor/docker-asciidoctor
  - docker pull mrshu/texlive-dblatex

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - docker run -v .:/documents asciidoctor/docker-asciidoctor .ci/adoc-to-tex.sh rules
  - docker run -v .:/documents mrshu/texlive-dblatex .ci/tex-to-pdf.sh rules

  # Same thing for superteam rules
  - docker run -v .:/documents asciidoctor/docker-asciidoctor .ci/adoc-to-tex.sh superteam_rules
  - docker run -v .:/documents mrshu/texlive-dblatex .ci/tex-to-pdf.sh superteam_rules

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

after_script:
  - ./.ci/after_script.sh
